'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/ui/TopNav";
import { useEffect, useState } from "react";
import { Sidebar } from "@/components/layout/sidebar";
import { GlobalState, useGlobalState } from "./context/GlobalState";
import Initializer from "@/components/Initializer";
import { Toaster } from "@/components/ui/toaster";
import { ToastProviderWrapper } from "@/components/ui/useToast";
import Footer from "@/components/ui/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const [modalOpen, setModalOpen] = useState(false)

  const [userDetails, setUserDetails] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  const handleModalClick = () => {
    setModalOpen(!modalOpen)
  }

  useEffect(() => {
    setLoading(true)
    const getUserDetails = () => {
      const res = { "userId": "user-1", "name": "User 1" }
      setUserDetails(res)
    }

    getUserDetails()
    setLoading(false)

  }, [])

  if (loading) return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ></body>
    </html>
  )


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalState>
          <Toaster />
          <ToastProviderWrapper>
            <TopNav onModalClick={handleModalClick} />
            <Initializer userDetails={userDetails} />
            {modalOpen && <Sidebar onClose={handleModalClick} />}
            <div style={{ width: '80%', margin: '0 auto' }}>
              {children}
            </div>
          </ToastProviderWrapper>
        </GlobalState>
        <Footer />
      </body>
    </html>
  );
}
