'use client'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/ui/TopNav";
import { useEffect, useState } from "react";
import { Sidebar } from "@/components/layout/sidebar";
import { GlobalState, useGlobalState } from "./context/GlobalState";
import Initializer from "@/components/Initializer";
import { Toaster } from "@/components/ui/toaster";
import { ToastProviderWrapper } from "@/components/ui/useToast";
import Footer from "@/components/ui/footer";
import { SessionProvider } from "next-auth/react";
import { motion } from "framer-motion";
import { PageTransitionWrapper } from "./common/components/PageTransitionWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <GlobalState>
            <Toaster />
            <ToastProviderWrapper>
              {/* <PageTransitionWrapper> */}
              {children}
              {/* </PageTransitionWrapper> */}
            </ToastProviderWrapper>
          </GlobalState>
        </SessionProvider>
      </body>
    </html>
  );
}
